const recipeCtxKey = '__recipeCtx__';

const RECIPE_GET_LIST = `${recipeCtxKey}/RECIPE_GET_LIST`;
const RECIPE_GET_LIST_SUCCESS = `${recipeCtxKey}/RECIPE_GET_LIST_SUCCESS`;
const RECIPE_GET_LIST_FAILURE = `${recipeCtxKey}/RECIPE_GET_LIST_FAILURE`;
const RECIPE_CLEAR_LIST = `${recipeCtxKey}/RECIPE_CLEAR_LIST`;

const RECIPE_GET_DETAIL = `${recipeCtxKey}/RECIPE_GET_DETAIL`;
const RECIPE_GET_DETAIL_SUCCESS = `${recipeCtxKey}/RECIPE_GET_DETAIL_SUCCESS`;
const RECIPE_GET_DETAIL_FAILURE = `${recipeCtxKey}/RECIPE_GET_DETAIL_FAILURE`;

const RECIPE_ADMIN_GET_LIST = `${recipeCtxKey}/RECIPE_ADMIN_GET_LIST`;
const RECIPE_ADMIN_GET_LIST_SUCCESS = `${recipeCtxKey}/RECIPE_ADMIN_GET_LIST_SUCCESS`;
const RECIPE_ADMIN_GET_LIST_FAILURE = `${recipeCtxKey}/RECIPE_ADMIN_GET_LIST_FAILURE`;

export {
    RECIPE_GET_LIST,
    RECIPE_GET_LIST_FAILURE,
    RECIPE_GET_LIST_SUCCESS,
    RECIPE_CLEAR_LIST,
    RECIPE_GET_DETAIL,
    RECIPE_GET_DETAIL_FAILURE,
    RECIPE_GET_DETAIL_SUCCESS,
    RECIPE_ADMIN_GET_LIST,
    RECIPE_ADMIN_GET_LIST_FAILURE,
    RECIPE_ADMIN_GET_LIST_SUCCESS,
};
