const authCtxKey = '__authCtx__';

const AUTH_SUCCESS = `${authCtxKey}/AUTH_SUCCESS`;
const AUTH_LOGOUT = `${authCtxKey}/AUTH_LOGOUT`;

const AUTH_GET_PROFILE = `${authCtxKey}/AUTH_GET_PROFILE`;
const AUTH_GET_PROFILE_SUCCESS = `${authCtxKey}/AUTH_GET_PROFILE_SUCCESS`;
const AUTH_GET_PROFILE_FAILURE = `${authCtxKey}/AUTH_GET_PROFILE_FAILURE`;
const AUTH_UPDATE_PROFILE_SUCCESS = `${authCtxKey}/AUTH_UPDATE_PROFILE_SUCCESS`;
const AUTH_UPDATE_PROFILE_IMAGE_URL = `${authCtxKey}/AUTH_UPDATE_PROFILE_IMAGE_URL`;

export {
    AUTH_SUCCESS,
    AUTH_LOGOUT,
    AUTH_GET_PROFILE,
    AUTH_GET_PROFILE_SUCCESS,
    AUTH_GET_PROFILE_FAILURE,
    AUTH_UPDATE_PROFILE_SUCCESS,
    AUTH_UPDATE_PROFILE_IMAGE_URL,
};
