export default {
    HOME: '/home',
    LOGIN: '/signin',
    REGISTER: '/sign-up',
    PROFILE: '/profile',
    EDIT_PROFILE: '/edit-profile',
    // RECIPE: '/recipe/:recipe_id',
    // UPDATE_INFO: '/update-info',
    RICIPE_DETAIL: '//recipe-detail/:dishId',
    // CREATE_RECIPE: '/create-recipe',
    // EDIT_RECIPE: '/edit-recipe',
    SEARCH: '/search',
    FORGOT_PASSWORD: '/forgot-password',
    // USER: '/user/:user_id',
    // BLOG: '/blog/:id',
    // OTHER_PROFILE: '/profilepage',
    // BLOG_LIST: '/blog-list',
    ERROR_PAGE: '/error',
};
