const blogCtxKey = '__blogCtx__';

const BLOG_GET_LIST = `${blogCtxKey}/BLOG_GET_LIST`;
const BLOG_GET_LIST_SUCCESS = `${blogCtxKey}/BLOG_GET_LIST_SUCCESS`;
const BLOG_GET_LIST_FAILURE = `${blogCtxKey}/BLOG_GET_LIST_FAILURE`;
const BLOG_CLEAR_LIST = `${blogCtxKey}/BLOG_CLEAR_LIST`;

const BLOG_GET_DETAIL = `${blogCtxKey}/BLOG_GET_DETAIL`;
const BLOG_GET_DETAIL_SUCCESS = `${blogCtxKey}/BLOG_GET_DETAIL_SUCCESS`;
const BLOG_GET_DETAIL_FAILURE = `${blogCtxKey}/BLOG_GET_DETAIL_FAILURE`;
const BLOG_DETAIL_CLEAR = `${blogCtxKey}/BLOG_DETAIL_CLEAR`;
const BLOG_INCREASE_NUM_OF_COMMENTS = `${blogCtxKey}/BLOG_INCREASE_NUM_OF_COMMENTS`;

const BLOG_GET_COMMENTS = `${blogCtxKey}/BLOG_GET_COMMENTS`;
const BLOG_GET_COMMENTS_SUCCESS = `${blogCtxKey}/BLOG_GET_COMMENTS_SUCCESS`;
const BLOG_GET_COMMENTS_FAILURE = `${blogCtxKey}/BLOG_GET_COMMENTS_FAILURE`;
const BLOG_UPDATE_COMMENT_CONTENT = `${blogCtxKey}/BLOG_UPDATE_COMMENT_CONTENT`;

const BLOG_GET_LIST_PENDING = `${blogCtxKey}/BLOG_GET_LIST_PENDING`;
const BLOG_GET_LIST_PENDING_SUCCESS = `${blogCtxKey}/BLOG_GET_LIST_PENDING_SUCCESS`;
const BLOG_GET_LIST_PENDING_FAILURE = `${blogCtxKey}/BLOG_GET_LIST_PENDING_FAILURE`;
const BLOG_CLEAR_LIST_PENDING = `${blogCtxKey}/BLOG_CLEAR_LIST_PENDING`;
const BLOG_REMOVE_ITEM_FROM_LIST_PENDING = `${blogCtxKey}/BLOG_REMOVE_ITEM_FROM_LIST_PENDING`;

const BLOG_LIKE_ITEM_SUCCESS = `${blogCtxKey}/BLOG_LIKE_ITEM_SUCCESS`;
const BLOG_DISLIKE_ITEM_SUCCESS = `${blogCtxKey}/BLOG_DISLIKE_ITEM_SUCCESS`;
const BLOG_LIKE_ITEM_DETAIL_SUCCESS = `${blogCtxKey}/BLOG_LIKE_ITEM_DETAIL_SUCCESS`;
const BLOG_DISLIKE_ITEM_DETAIL_SUCCESS = `${blogCtxKey}/BLOG_DISLIKE_ITEM_DETAIL_SUCCESS`;

const BLOG_GET_COMMENT_REPORT_LIST = `${blogCtxKey}/BLOG_GET_COMMENT_REPORT_LIST`;
const BLOG_GET_COMMENT_REPORT_LIST_SUCCESS = `${blogCtxKey}/BLOG_GET_COMMENT_REPORT_LIST_SUCCESS`;
const BLOG_GET_COMMENT_REPORT_LIST_FAILURE = `${blogCtxKey}/BLOG_GET_COMMENT_REPORT_LIST_FAILURE`;
const BLOG_REMOVE_COMMENT_REPORT_FROM_LIST = `${blogCtxKey}/BLOG_REMOVE_COMMENT_REPORT_FROM_LIST`;

export {
    BLOG_GET_LIST,
    BLOG_GET_LIST_FAILURE,
    BLOG_GET_LIST_SUCCESS,
    BLOG_CLEAR_LIST,
    BLOG_GET_DETAIL,
    BLOG_GET_DETAIL_FAILURE,
    BLOG_GET_DETAIL_SUCCESS,
    BLOG_GET_COMMENTS,
    BLOG_GET_COMMENTS_SUCCESS,
    BLOG_GET_COMMENTS_FAILURE,
    BLOG_GET_LIST_PENDING,
    BLOG_GET_LIST_PENDING_FAILURE,
    BLOG_GET_LIST_PENDING_SUCCESS,
    BLOG_DETAIL_CLEAR,
    BLOG_LIKE_ITEM_SUCCESS,
    BLOG_DISLIKE_ITEM_SUCCESS,
    BLOG_LIKE_ITEM_DETAIL_SUCCESS,
    BLOG_DISLIKE_ITEM_DETAIL_SUCCESS,
    BLOG_CLEAR_LIST_PENDING,
    BLOG_REMOVE_ITEM_FROM_LIST_PENDING,
    BLOG_GET_COMMENT_REPORT_LIST,
    BLOG_GET_COMMENT_REPORT_LIST_SUCCESS,
    BLOG_GET_COMMENT_REPORT_LIST_FAILURE,
    BLOG_UPDATE_COMMENT_CONTENT,
    BLOG_REMOVE_COMMENT_REPORT_FROM_LIST,
    BLOG_INCREASE_NUM_OF_COMMENTS,
};
