const accountCtxKey = '__accountCtx__';

const ACCOUNT_GET_LIST = `${accountCtxKey}/ACCOUNT_GET_LIST`;
const ACCOUNT_GET_LIST_SUCCESS = `${accountCtxKey}/ACCOUNT_GET_LIST_SUCCESS`;
const ACCOUNT_GET_LIST_FAILURE = `${accountCtxKey}/ACCOUNT_GET_LIST_FAILURE`;
const ACCOUNT_CLEAR_LIST = `${accountCtxKey}/ACCOUNT_CLEAR_LIST`;
const ACCOUNT_REMOVE_LIST_ITEM = `${accountCtxKey}/ACCOUNT_REMOVE_LIST_ITEM`;
const ACCOUNT_UPDATE_ROLE_SUCESS = `${accountCtxKey}/ACCOUNT_UPDATE_ROLE_SUCESS`;

const ACCOUNT_GET_DETAIL = `${accountCtxKey}/ACCOUNT_GET_DETAIL`;
const ACCOUNT_GET_DETAIL_SUCCESS = `${accountCtxKey}/ACCOUNT_GET_DETAIL_SUCCESS`;
const ACCOUNT_GET_DETAIL_FAILURE = `${accountCtxKey}/ACCOUNT_GET_DETAIL_FAILURE`;

export {
    ACCOUNT_GET_LIST,
    ACCOUNT_GET_LIST_FAILURE,
    ACCOUNT_GET_LIST_SUCCESS,
    ACCOUNT_CLEAR_LIST,
    ACCOUNT_GET_DETAIL,
    ACCOUNT_GET_DETAIL_FAILURE,
    ACCOUNT_GET_DETAIL_SUCCESS,
    ACCOUNT_REMOVE_LIST_ITEM,
    ACCOUNT_UPDATE_ROLE_SUCESS,
};
